apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-demo-deployment
  labels:
    app: full-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: full-demo
  template:
    metadata:
      labels:
        app: full-demo
    spec:
      containers:
        - name: full-demo
          image: quarkus/full-demo-jvm
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: full-demo-service
spec:
  type: NodePort
  selector:
    app: full-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30111
